url: http://ostholstein.freifunk.net

community:
  # Metadata
  name: "Ostholstein"

  # Custom URLs
  url_wiki:  "http://luebeck.freifunk.net/wiki/Ostholstein"
  url_geomap: "/map/geomap.html"
  url_graph: "/map/graph.html"
  url_nodelist: "/map/list.html"
  url_mailman: "http://lists.ostholstein.freifunk.net/mailman/listinfo/list"
  url_logo: "/images/ffoh-logo.png"

  # Mail Contacts
  mail_info: "info@ostholstein.freifunk.net"
  mail_keys: "keys@ostholstein.freifunk.net"
  mail_discussion: "discussion@ostholstein.freifunk.net"

  # Other Contacts
  #sip: ["space@sip.ffoh", "space@10.254.254.254"] # Optional
  #twitter: "FreifunkOstholstein" # Optional
  #irc: "#ffoh"

  # GPS
  geo_lat: 54.010162934330765 
  geo_lon: 10.79681396484375

firmware:
  base: "http://ostholstein.freifunk.net/firmware/stable/"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/smoe/site-ffoh"
  # Path to local checkout of the site repo
  gluon_site_dir: "../gluon/site"
